exclude: ^.*(medic/settings|/migrations/|/.env.template/|/\.github/|/static/|/media/).*$
default_language_version:
  python: python3.12
files: '\.py$'
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
